sonar.projectKey=sourcerer-app
sonar.organization=aline-capucho
sonar.projectName=sourcerer-app

sonar.host.url=https://sonarcloud.io

# Source
sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
sonar.sourceEncoding=UTF-8
sonar.java.binaries=build/classes

# Exclusions
sonar.exclusions=build/**,**/generated/**,**/proto/**
sonar.coverage.exclusions=**/test/**

# Language
sonar.language=kotlin
sonar.kotlin.file.suffixes=.kt
